modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''
AE2Enhanced multiblock extension.
'''

[[dependencies.ae2enhanced]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ae2enhanced]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.ae2enhanced]]
modId="ae2"
mandatory=true
versionRange="[15.3.4,)"
ordering="AFTER"
side="BOTH"
